package com.grantfinder.crawler;

public enum CrawlSource {
    MANUAL,
    POETS_WRITERS,
    GRANTS_GOV,
    FUNDSFORWRITERS,
    WEARETEACHERS,
    STAYINGCOOL_LIBRARY,
    BOOKRETRIEVER,
    ALLEDUCATIONSCHOOLS,
    KFA_NONPROFIT,
    NEA_FOUNDATION,
    RISEVISION,
    PLANBOOK,
    OZOBOT,
    SOLIDPROFESSOR,
    CONNECT4EDUCATION,
    WATERFORD,
    PROGRESSLEARNING,
    TEACH_COM,
    NEXTWAVESTEM,
    CHILDRENSMUSICWORKSHOP
}
